import {estimateDestination, estimateDistance, validateArtifact} from './runtime/ride_planning_runtime.js';
const presets=[['collection','カード収集',10,true],['lunch','昼食',40,true],['snack','軽食',20,false],['sightseeing','観光・見学',30,false],['other','その他',10,false]];
let artifact;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const duration=sec=>{const m=Math.floor(sec/60+.5),h=Math.floor(m/60);return h?`${h}時間${String(m%60).padStart(2,'0')}分`:`${m}分`};
const km=value=>`${Number(value).toFixed(1)} km`;
function eventRows(){return presets.map(([code,label,minutes,checked])=>`<div class="event"><label><input type="checkbox" name="selected_event" value="${code}"${checked?' checked':''}><span>${label}</span></label><label class="minutes"><input type="number" name="event_${code}" value="${minutes}" min="0" step="1" inputmode="numeric"><span>分</span></label></div>`).join('')}
document.querySelectorAll('[data-events]').forEach(node=>node.innerHTML=eventRows());
function selected(form){return [...form.querySelectorAll('[name=selected_event]:checked')].map(box=>{const v=Number(new FormData(form).get(`event_${box.value}`));if(!Number.isInteger(v)||v<0)throw new Error('予定イベント時間は0以上の整数で入力してください。');return v})}
function epoch(time,deadline=false){const now=new Date(),parts=time.split(':').map(Number);const date=new Date(now.getFullYear(),now.getMonth(),now.getDate(),parts[0],parts[1]);if(deadline)return date.getTime()/1000;return date.getTime()/1000}
function clock(departureEpoch,arrivalEpoch){const d=new Date(arrivalEpoch*1000),days=Math.floor((arrivalEpoch-departureEpoch)/86400);return `${days>0?'翌日 ':''}${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function allocation(moving,planned,other){const total=moving+planned+other;if(total<=0)return '<div class="notice">データがありません</div>';let x=0;return `<svg class="allocation" viewBox="0 0 100 1" preserveAspectRatio="none" aria-label="中央予測の時間配分">${[[moving,'moving-fill'],[planned,'planned-fill'],[other,'other-fill']].filter(([v])=>v>0).map(([v,c],i,a)=>{const width=i===a.length-1?100-x:v/total*100;const rect=`<rect class="${c}" x="${x}" width="${width}" height="1"/>`;x+=width;return rect}).join('')}</svg>`}
const component=(kind,icon,title,copy,value)=>`<div class="component ${kind}"><span class="icon">${icon}</span><span class="copy"><strong>${title}</strong><br><small>${copy}</small></span><span class="value">${value}</span></div>`;
function warning(codes){return codes.includes('residual_ols_long_distance_low_evidence')?'<div class="notice">150km以上は過去の対象ライドが少なく、予測誤差が大きい可能性があります。</div>':''}
function reveal(node,html){node.innerHTML=html.replace('<h1>計算結果</h1>','<h1>計算結果（概要）</h1>');node.scrollIntoView({behavior:'smooth',block:'start'})}
function directResult(r,input){return `<section class="result"><h1>計算結果</h1><div class="summary"><div><span>出発時刻</span><strong>${esc(input.departure_time)}</strong></div><b class="arrow">→</b><div><span>予想帰宅時刻</span><strong>${clock(input.epoch,r.arrival_lower_at)} 〜 ${clock(input.epoch,r.arrival_upper_at)}</strong><i class="central">中央予測 ${clock(input.epoch,r.arrival_at)}</i></div><div class="total"><span>所要時間</span><strong>${duration(r.elapsed_lower_sec)} 〜 ${duration(r.elapsed_upper_sec)}</strong><br><i class="central">中央予測 ${duration(r.elapsed_time_sec)}</i></div></div><h2>所要時間の内訳</h2>${allocation(r.moving_time_sec,r.planned_event_time_sec,r.residual_nonmoving_time_sec)}<div class="breakdown">${component('moving','走','走行時間（移動）','信号待ち、補給、短い休憩などを含む',duration(r.moving_time_sec))}${component('planned','予','予定イベント時間','ユーザーが入力したイベントの合計',duration(r.planned_event_time_sec))}${component('other','他','その他','休憩、渋滞、天候・体調による停止など',`${duration(r.residual_lower_sec)} 〜 ${duration(r.residual_upper_sec)}<br><i class="central">中央予測 ${duration(r.residual_nonmoving_time_sec)}</i>`)}</div>${warning(r.warnings)}</section>`}
function distanceResult(r,input){const movingLow=r.available_time_sec-r.planned_event_time_sec-r.residual_upper_sec,movingHigh=r.available_time_sec-r.planned_event_time_sec-r.residual_lower_sec;return `<section class="result"><h1>計算結果</h1><h2 class="distance-range">${km(r.distance_lower_km)} 〜 ${km(r.distance_upper_km)}</h2><p class="central">中央予測 ${km(r.prototype_max_distance_km)}</p><div class="fixed"><div><span>出発時刻</span><br><strong>${esc(input.departure_time)}</strong></div><b>→</b><div><span>帰宅期限</span><br><strong>${esc(input.deadline_time)}</strong></div><div><span>利用可能時間</span><br><strong>${duration(r.available_time_sec)}</strong></div></div><h2>時間配分の内訳</h2>${allocation(r.moving_time_sec,r.planned_event_time_sec,r.residual_nonmoving_time_sec)}<div class="breakdown">${component('moving','走','走行に使える時間（移動）','信号待ち、補給、短い休憩などを含む',`${duration(movingLow)} 〜 ${duration(movingHigh)}<br><i class="central">中央予測 ${duration(r.moving_time_sec)}</i>`)}${component('planned','予','予定イベント時間','ユーザーが入力したイベントの合計',duration(r.planned_event_time_sec))}${component('other','他','その他','休憩、渋滞、天候・体調による停止など',`${duration(r.residual_lower_sec)} 〜 ${duration(r.residual_upper_sec)}<br><i class="central">中央予測 ${duration(r.residual_nonmoving_time_sec)}</i>`)}</div>${warning(r.warnings)}</section>`}
document.querySelectorAll('.mode-nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.mode-nav button').forEach(b=>b.classList.toggle('active',b===button));document.querySelector('#destination-view').classList.toggle('hidden',button.dataset.mode!=='destination');document.querySelector('#distance-view').classList.toggle('hidden',button.dataset.mode!=='distance')}));
document.querySelectorAll('[data-time]').forEach(button=>button.addEventListener('click',()=>button.closest('form').elements.departure_time.value=button.dataset.time));
document.querySelectorAll('.current-time').forEach(button=>button.addEventListener('click',()=>{const n=new Date();button.closest('form').elements.departure_time.value=`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`}));
document.querySelector('#destination-form').addEventListener('submit',event=>{event.preventDefault();const node=document.querySelector('#destination-result');try{const form=event.currentTarget,d=Number(form.elements.distance_km.value),time=form.elements.departure_time.value,e=epoch(time),r=estimateDestination({distance_km:d,departure_epoch_sec:e,event_minutes:selected(form)},artifact);reveal(node,directResult(r,{departure_time:time,epoch:e}))}catch(e){reveal(node,`<div class="error">${esc(e.message)}</div>`)}});
document.querySelector('#distance-form').addEventListener('submit',event=>{event.preventDefault();const node=document.querySelector('#distance-result');try{const form=event.currentTarget,s=form.elements.departure_time.value,d=form.elements.deadline_time.value,start=epoch(s),end=epoch(d);if(end<=start)throw new Error('帰宅期限は出発時刻より後にしてください。');const r=estimateDistance({departure_epoch_sec:start,deadline_epoch_sec:end,event_minutes:selected(form)},artifact);reveal(node,distanceResult(r,{departure_time:s,deadline_time:d}))}catch(e){reveal(node,`<div class="error">${esc(e.message)}</div>`)}});
fetch('./artifacts/ride_planning_runtime_v1.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('予測データを読み込めません。');return r.json()}).then(value=>{artifact=validateArtifact(value)}).catch(error=>{const node=document.querySelector('#fatal');node.textContent=`${error.message} 初回利用またはcache消去後は、通信可能な状態で開き直してください。`;node.classList.remove('hidden');document.querySelectorAll('form button').forEach(b=>b.disabled=true)});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js');
